-- =============================================================================
-- Add review_logs table
--
-- The existing `reviews` table stores the *current* FSRS card state (1:1 per
-- card). This table stores each individual *review event* — what rating was
-- given, when, and what the card's FSRS state was at that moment.
--
-- These map directly to ts-fsrs's ReviewLog type (item.log from RecordLogItem).
-- The fields below mirror that interface exactly so the frontend can insert
-- without any transformation.
-- =============================================================================

CREATE TABLE public.review_logs (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at  timestamp with time zone NOT NULL DEFAULT now(),

  -- Which card and member this event belongs to.
  -- CASCADE means history is cleaned up automatically when a card is deleted.
  card_id     bigint NOT NULL REFERENCES public.cards(id) ON DELETE CASCADE,
  member_id   uuid   NOT NULL REFERENCES public.members(id) ON DELETE CASCADE,

  -- FSRS ReviewLog fields (ts-fsrs RecordLogItem.log)
  rating            smallint NOT NULL,  -- 1=Again 2=Hard 3=Good 4=Easy
  state             smallint NOT NULL,  -- 0=New 1=Learning 2=Review 3=Relearn
  due               timestamp with time zone NOT NULL,  -- when the card was due
  stability         real,
  difficulty        real,
  elapsed_days      smallint,
  last_elapsed_days smallint,
  scheduled_days    smallint,
  review            timestamp with time zone NOT NULL   -- when review happened
);

ALTER TABLE public.review_logs ENABLE ROW LEVEL SECURITY;

-- Members can only see and insert their own review logs.
-- No UPDATE or DELETE — this table is append-only by design.
CREATE POLICY "Members can insert their own review logs"
  ON public.review_logs
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = member_id);

CREATE POLICY "Members can view their own review logs"
  ON public.review_logs
  FOR SELECT
  TO authenticated
  USING (auth.uid() = member_id);

-- Index for the most common query patterns:
--   - All logs for a card (history view, rollback)
--   - All logs for a member in a time range (analytics dashboard)
CREATE INDEX review_logs_card_id_idx    ON public.review_logs (card_id);
CREATE INDEX review_logs_member_id_idx  ON public.review_logs (member_id, review DESC);

-- Grant access (matches the pattern of other tables)
GRANT SELECT, INSERT ON public.review_logs TO authenticated;
GRANT ALL ON public.review_logs TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.review_logs_id_seq TO authenticated;
