name: Deploy to Production

on:
  release:
    types: [published]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    name: Deploy
    uses: ./.github/workflows/deploy.yml
    with:
      environment: production
    secrets: inherit
